apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: audi-showroom
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64("root")

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: audi-showroom
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.3
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "audi_db"
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
