apiVersion: v1
kind: Service
metadata:
  name: audi-showroom
  namespace: audi-showroom
spec:
  type: LoadBalancer
  selector:
    app: audi-showroom
    color: blue   # Default to blue color, deploy script will patch this selector between blue <-> green
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088
